### ISSUE TITLE
Screenshots should respect Screenshot plugin settings, or provide their own

### ISSUE THREAD

**Issue by Enriath** [Nightfirecat/plugin-hub-plugins#1]
Personally I have screenshot frame disabled, and I'd like for my virtual level screenshots to look the same as the <=99 ones.

I also have Custom Chrome disabled, which breaks the top. Not sure if it happens with the vanilla screenshot plugin. Linux Mint 19, with Gala WM

(Had to screenshot my image viewer since GitHub didn't show the empty space)
![image](https://user-images.githubusercontent.com/2979691/79002816-2f066a00-7b49-11ea-9db6-5743c1cc4fe6.png)

**Comment by Nightfirecat** [comment]
Fixed in 7cc036388214e961165dcc1e46474e48eb1c6259
