### ISSUE TITLE
Relog after gaining virtual level fires level up event again

### ISSUE THREAD

**Issue by Broooklyn** [Nightfirecat/plugin-hub-plugins#10]
After gaining 200m in a skill I relogged immediately upon receiving the level up message. After logging in again, the fireworks animation continued to play and the level-up message/screenshot occured again, leaving me with multiple 200m screenshots.

**Comment by Nightfirecat** [comment]
Very likely related to #8 or #9

**Comment by Nightfirecat** [comment]
Fixed in runelite/plugin-hub#928
