### ISSUE TITLE
Option to use nicknames rather than actual names. (Nibbler, Bat, Blob, Melee, Mage, Ranger, Jad, Zuk)

### ISSUE THREAD

**Issue by bluelightzero** [Nightfirecat/plugin-hub-plugins#11]
It's really common to not use the actual names:

From the [wiki](https://oldschool.runescape.wiki/w/Inferno#Wave_breakdown):

![image](https://user-images.githubusercontent.com/4492982/107161265-6fb25800-6993-11eb-9417-6c7b800de128.png)

**Comment by Nightfirecat** [comment]
This has been added as of runelite/plugin-hub#1078. Restart your client then use the added "Use common names" config option
