### ISSUE TITLE
Customizable color?

### ISSUE THREAD

**Issue by Anonymous75** [Nightfirecat/plugin-hub-plugins#17]
Currently, we can't change the color of the line from the default bright red color. I understand the whole point of the plugin is to make a specified area more visible, but I think adding an option to customize the appearance of the line would be an improvement.

Would it be possible to add a "color picker" (similar to many other Runelite plugins)? Including adjustable opacity would also be appreciated.

**Comment by Nightfirecat** [comment]
The intent was very much to choose a color which stands out. I could see a use case for reducing the opacity of the lines if players don't like how vibrant they are. Besides opacity adjustment, is there a particular reason you would want them to be some color besides red? (and orange for the spear lines)

**Comment by Anonymous75** [comment]
My main reason is that I use the color red to highlight other players using the Player Indicators plugin. I could adjust the colors in that plugin, but I'd rather keep them as-is since I'm used to them. 

Not sure if that's a good reason but I figured I'd mention it anyway.

**Comment by Nightfirecat** [comment]
That makes sense. I'll go ahead and add some color configs for the overlay then.

**Comment by Nightfirecat** [comment]
Added in d20588d1bda7f7e4d0f2e4fffe6e4ebccd88d89b, and released in v1.1.
