### ISSUE TITLE
Wilderness-multi-lines: missing tiles

### ISSUE THREAD

**Issue by Newbcake** [Nightfirecat/plugin-hub-plugins#18]
The two marked tiles, including the one I'm standing on are multi but are marked as singles by the plugin

![RuneLite_2023-01-30_17-43-24](https://user-images.githubusercontent.com/9064744/215540034-9f147368-fb90-4557-9e9a-12baaaf847c1.png)

**Comment by Nightfirecat** [comment]
Oh, these must also have been fixed the last time Bounty Hunter was active--I wasn't aware of that. I'll confirm that ingame and get that fixed today.

**Comment by Nightfirecat** [comment]
Added in dad7c346a7135d355a8edeb13ad8f64302265df2, and released on the plugin hub as v1.1.2 in runelite/plugin-hub@947e3465d9b2abf588af6cfaf607837a03714d9e
