### ISSUE TITLE
Display lines for different Wilderness levels

### ISSUE THREAD

**Issue by Z7-z** [Nightfirecat/plugin-hub-plugins#20]
I would like to be able to see lines in the wilderness for different levels, whether it's every single level (might be a bit of an eyesore), or my preferential proposal, the main levels of Level 20 and Level 30. 
This would work in conjuction with the excellent multiline and spearline already implemented so you could see exactly when you're in Level 30 and can teleport away from those pesky PKers that are all in Discord at 4am trying to get your spade.

**Comment by Nightfirecat** [comment]
I'm not certain I'd want to include this, though if I did I would want to rename the plugin to reflect its more general "Wilderness Lines" behavior

**Comment by Z7-z** [comment]
Why the hesitance may I ask? You could theoretically tile the entire level 30 line just like the multi & spear line, but this wonderful plugin just makes it easier

**Comment by Nightfirecat** [comment]
The rationale is that I wrote this plugin (and all my plugins really) to be very specific in scope, and would rather not keep adding more and more features, thereby increasing the maintenance load I would have to manage to keep them running and in good shape. With that said, I've thought this one over for a while and decided this would be a small enough addition and probably a well-received one to add 20/21 and 30/31 lines for a slim but multi-purpose "wilderness lines" plugin.

**Comment by Z7-z** [comment]
nightfirecat I wholeheartedly agree with you wanting to add this I think whoever suggested it is very smart, thank you for letting this feature through you are a kind cat

**Comment by Nightfirecat** [comment]
Added in 2be9a87a7852d323311a02cbb8e810ed07df825b, and released on the plugin hub in runelite/plugin-hub@6d2d161fcc2bfc2d1eec1b89cae0a3a3387658fd.

**Comment by Z7-z** [comment]
excellent work nightfiredog
