### ISSUE TITLE
[Fight Cave Waves] When Inferno is paused after wave completion, plugin acts as if the next wave has begun

### ISSUE THREAD

**Issue by fuzxi** [Nightfirecat/plugin-hub-plugins#23]
![2023-07-19-02-16-10](https://github.com/Nightfirecat/plugin-hub-plugins/assets/33790641/3f9d88e7-b0ee-4b11-ae36-ed180970346a)
The Inferno was paused after I completed wave 45, but the plugin displays the current wave as 46 and the next wave as 47. This will be true when I log back in, but until then it can be confusing when only using the "next wave" display, as the wave it's showing as next is actually two waves ahead.
I think you're just incrementing the counter when the game chat prints "Wave complete!", so maybe this can be fixed by just decrementing the counter if game chat prints "The Inferno has been paused. You may now log out."

**Comment by Nightfirecat** [comment]
I definitely hadn't done any testing for the wave pausing case, so I'm not surprised this isn't working properly there. I'll get this fixed, but can't promise it'll be right away.

**Comment by Nightfirecat** [comment]
Fixed in 9e911ee723c0bc8c5bfb91d177e9426d0ba3917e and updated on the plugin hub in runelite/plugin-hub@0d8c8520fcfa5a407f394148056be8bdcb71b366

**Comment by fuzxi** [comment]
Cheers!
