### ISSUE TITLE
Inferno Current Wave

### ISSUE THREAD

**Issue by Th3mike** [Nightfirecat/plugin-hub-plugins#25]
Currently in inferno it only shows the current wave if it has the BOTH option, it would be nice if it had the next wave number in the interface

**Comment by Nightfirecat** [comment]
Sorry, I look at this code once in a blue moon. Can you explain in a bit more detail what you want changed here? (screenshots would help)

**Comment by Nightfirecat** [comment]
@Th3mike could you provide some more info here?

**Comment by Nightfirecat** [comment]
I don't really understand what's being asked here and no further details have been provided, so I'm closing this issue.
