### ISSUE TITLE
Missing multi line northeast of lumberyard

### ISSUE THREAD

**Issue by evilgenious448** [Nightfirecat/plugin-hub-plugins#26]
The area north east of the Lumbermill (just north of Zemouregal's Base trapdoor) is a multi-combat zone, Tested it myself, see in screenshot below:
![image](https://github.com/Nightfirecat/plugin-hub-plugins/assets/32331499/a08bd819-0aee-4c96-a6ea-1d23c4aec985)

Also source:
https://youtube.com/clip/UgkxaJj7xDd4WcNonn4KAsx-Vm_Q6d11edZu?si=v-drEZRAnojhcJqB

**Comment by Nightfirecat** [comment]
Added in 015d94881d3e235f3039d03da3b2373bd7c1fe20, and released to the plugin hub as version 1.3.2 in runelite/plugin-hub@ead0b50a43c27f86aa5ba4a6ae83c78a3aa1716d.
