### ISSUE TITLE
Request: Add a wilderness line that indicates the level below which your current opponent cannot attack you

### ISSUE THREAD

**Issue by NoahTingey** [Nightfirecat/plugin-hub-plugins#28]
Basically title. But to explain further in case it's not clear:

If I'm at 100 combat level and I'm in combat with a 105 combat lvl player, it would be nice if there was a line at 5 wilderness so I know how close I am to escape. 

In addition to being just a nice visual indicator, it would also be useful to know exactly _where_ the line is (as opposed to just running past it until I notice I'm already below 5 wildy) so I can tick-perfectly activate my raspberry emote as I cross over the line ;)

**Comment by Nightfirecat** [comment]
Hey, thanks for submitting a request. Unfortunately I'm not interested in adding this feature at this time--for one, I don't want to deal with tracking possibly weird cases when in multi-combat, and for two, I don't feel it's a good fit for this plugin.
