### ISSUE TITLE
Missing multi line near southern rev cave entrance

### ISSUE THREAD

**Issue by ctauskey** [Nightfirecat/plugin-hub-plugins#29]
There is 2x1 area directly west of the southern rev cave entrance that is multi but shown as singles with this plug in

**Comment by Nightfirecat** [comment]
Added in b8d63d0bf827eb40b70bfb9c1422f7ad57147139, and released to the plugin hub as version 1.3.2 in runelite/plugin-hub@ead0b50a43c27f86aa5ba4a6ae83c78a3aa1716d.
