### ISSUE TITLE
Virtual level ups sometimes do not fire

### ISSUE THREAD

**Issue by SieBRUM** [Nightfirecat/plugin-hub-plugins#7]
Hey, I have been using this plugin for a while now. Love it :)
Today, I leveled my farming but I did not receive the level-up message and it did not make a screeshot. 

As shown in the GIF, it does not work.
https://thumbs.gfycat.com/SophisticatedFlatAlabamamapturtle-mobile.mp4

Installed version:
![image](https://user-images.githubusercontent.com/14212955/95067088-90c41d00-0703-11eb-9d6d-7f6975e30e09.png)
Settings:
![image](https://user-images.githubusercontent.com/14212955/95067097-9457a400-0703-11eb-8a20-8d523b0e4831.png)

As I said, I have been using the plugin for quite a while now, and I have a ton of screenshots post-99 made by this plugin.

**Comment by Nightfirecat** [comment]
I've had at least one other person say that it intermittently doesn't work for virtual level ups. I haven't experienced it myself yet and I don't know offhand how it could not work sometimes, but I'll take a look at this later and see if anything turns up.

**Comment by runeliteissuesmaker** [comment]
I was the other person who had the issue with not getting a level up, mine was also with farming, perhaps there is an issue with checking the health of the tree stopping the interface showing up?

**Comment by Nightfirecat** [comment]
I can say I've encountered this a couple times during Trailblazer leagues and suspect it has to do with getting an xp drop which would gain a virtual level after a loading screen. I don't expect to have a fix for this before leagues are done, but I will test on this further once they're finished.

**Comment by Nightfirecat** [comment]
Fixed in runelite/plugin-hub#928
